id = "pwn-easy-shellcoding"
name = "Easy Shellcoding"
author = "unvariant"
description = "I am sure that my shellcode sandbox is impossible to escape!"
category = "pwn"
points.min = 50
points.max = 500
visible = true

[flag]
file = "work/flag"

[container.default]
build = "work/"
privileged = true
expose = { 5000 = "tcp" }

[[provide]]
dir = "dist/"
as = "easy-shellcoding"
