id = "misc-snake"
name = "snake"
author = "cinabun"
description = "lets play some snake"
category = "misc"
strategy = "instanced"
points.min = 50
points.max = 500

[flag]
file = "chall/flag.txt"

[container.default]
build = "chall/"

[container.default.expose]
5000 = "tcp"

[[provide]]
dir = "dist/"
as = "snake"

