id = "rev-normal-java-code"
name = "normal-java-code"
author = "cinabun"
description = "in 2004, I wrote a program to calculate the flag using the latest and greatest Java 1.5. It's still running to this day.\n\nNote: flag wrapper is `amateursctf{...}`, NOT `amateursCTF{...}`"
category = "rev"
points.min = 50
points.max = 500

[flag]
file = "src/flag.txt"

[[provide]]
dir = "dist/"
as = "normal-java-code"